name: PyPI

on:
  push:
    branches:
      - master
    tags:
      - v*

  pull_request:

  schedule:
    - cron: "0 5 * * 1"  # runs at 05:00 UTC on Mondays

jobs:
  publish:

    runs-on: ubuntu-latest

    env:
      REAKTORO_USE_OPENLIBM: 1
      NUMBER_OF_COMPILATION_JOBS: 2

    strategy:
      fail-fast: true
      max-parallel: 4

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Configuring Cache
        id: cache
        uses: actions/cache@v2
        env:
          # Increase this value to reset cache and rebuild the env during the PR
          CACHE_NUMBER: 1
        with:
          path: |
            **/build
            **/ccache
            ~/conda_pkgs_dir
          key:
            ${{ runner.os }}-${{ github.ref }}-${{ env.CACHE_NUMBER }}

      - uses: conda-incubator/setup-miniconda@v2
        with:
          use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!

      - name: Configuring Conda Environment
        shell: bash -l {0}
        env:
          PY_VER: 3.7
        run: |
          conda config --set always_yes yes --set changeps1 no
          conda config --add channels conda-forge
          conda install conda-devenv
          conda devenv

      - name: Building and Installing Reaktoro
        shell: bash -l {0}
        env:
          CC: ccache
          CXX: ccache
        run: |
          source activate reaktoro
          ccache -s
          ccache -z
          inv -e compile -n ${{ env.NUMBER_OF_COMPILATION_JOBS }}
          ccache -s
          python ci/check_compiled_files.py

      - name: Testing Reaktoro
        shell: bash -l {0}
        run: |
          source activate reaktoro
          pytest . -n auto

      - name: Publish Reaktoro to PyPI
        # if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          packages_dir: artifacts/python/dist
          repository_url: https://test.pypi.org/legacy/
          skip_existing: true
